import axios from 'axios'
import { IncomingMessage, ServerResponse } from 'http'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { decodeJwtFromCookie } from 'src/backend/api/auth'

interface Home {
  user: {
    id: string
    email: string
  }
}

const Home: React.FC<Home> = ({ user }) => {
  const router = useRouter()

  const logout = async () => {
    await axios.post('/api/signout')
    router.push('/signin')
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>
      <main>
        <h1>Home</h1>
        <p>{user.id}</p>
        <p>This page is private, {user.email}</p>
        <button onClick={() => logout()}>Sign out</button>
      </main>
    </>
  )
}

export default Home

export const getServerSideProps = async ({
  req,
  res,
}: {
  req: IncomingMessage
  res: ServerResponse<IncomingMessage>
}) => {
  const jwt = await decodeJwtFromCookie(req, res)
  return { props: { user: jwt.payload.user } }
}
